// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eucwtwejktcjxowiybjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Y3d0d2Vqa3Rjanhvd2l5Ymp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODczMTgsImV4cCI6MjA2OTE2MzMxOH0.a-w6KqL5C1GwyCoutH1pDQrrQCDxyH4noAPZNP9FzEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});